### ISSUE TITLE
Connection Failed unknow option type 30

### ISSUE THREAD

**Issue by martinfaust** [SAP/PyHDB#1]
Connection fails against HANA Rev 8x and 91.
Python 2.6 (r26:66714, May  6 2011, 15:10:21) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2

```
>>> import pyhdb
>>> connection = pyhdb.connect(   host="remote-host...",    port=30415,    user="SYSTEM",    password="....")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/__init__.py", line 24, in connect
    connection.connect()
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/client.py", line 140, in connect
    ConnectOptions(DEFAULT_CONNECTION_OPTIONS)
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/base.py", line 101, in send
    return self.connection._send_message(self.pack())
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/client.py", line 110, in _send_message
    return Message.unpack_reply(self, header, payload)
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/base.py", line 112, in unpack_reply
    payload, expected_segments=header[4]
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/base.py", line 230, in unpack_from
    yield ReplySegment.unpack(segment_header, segment_payload)
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/base.py", line 246, in unpack
    tuple(Part.unpack_from(payload, expected_parts=header[2]))
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/base.py", line 321, in unpack_from
    part_header[2], part_payload
  File "/usr/local/lib64/python2.6/site-packages/pyhdb-0.1.0-py2.6.egg/pyhdb/protocol/parts.py", line 125, in unpack_data
    raise Exception("Unknown option type %s" % typ)
Exception: Unknown option type 30
```

**Comment by TwoLaid** [comment]
The unknown type 30 is `NSTRING`, which has not been implemented for the Options Part. So you are getting this error while trying to parse the Connection Options you received from your HANA. The options include some basic information about the connection to your HANA. Interestingly, I have never seen a HANA that sent an option with the `NSTRING` type. Therefore, I cannot test this for myself but It should behave pretty much like `STRING` (29) so you could just change these two lines in the protocol/parts.py file:

https://github.com/TwoLaid/PyHDB/commit/7aaefa06a28d1c919c1485e0cfe98b2528ddbbf5

Remember to either re-install the module afterwards, or change it directly in your site-packages folder and delete the .pyc files. Alternatively, you could just pull that commit from my forked repository.

**Comment by TwoLaid** [comment]
Actually, I believe that your problem is not the lacking support of `NSTRING` but a bug that screws up the option parsing when an unknown option key is received. The `30` here is most likely random data from the next option.

Therefore I believe that your problem should be resolved with the bugfix in this pull request: https://github.com/SAP/PyHDB/pull/3

You could either pull it yourself (I see that you have forked this repository anyway), or wait for it to be merged into this repository

**Comment by martinfaust** [comment]
@TwoLaid Thanks a lot for fixing this.  @jarus , @bsrdjan When will you merge the PR? Its not the best SAP PR to have non-working code in public for weeks ...

**Comment by bsrdjan** [comment]
@TwoLaid, thank you very much for the fix.
