### ISSUE TITLE
Tests execution not working

### ISSUE THREAD

**Issue by arbulu89** [SAP/PyHDB#124]
Project tests execution is not working.
After installing `tox` and running it I have the next result (just for one of the py environments):

```
platform linux -- Python 3.6.5, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/_pytest/terminal.py", line 581, in pytest_sessionstart
INTERNALERROR>     config=self.config, startdir=self.startdir
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/tests/conftest.py", line 81, in pytest_report_header
INTERNALERROR>     hana = hana_system()
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/_pytest/fixtures.py", line 962, in result
INTERNALERROR>     fail(message, pytrace=False)
INTERNALERROR>   File "/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/lib/python3.6/site-packages/_pytest/outcomes.py", line 119, in fail
INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
INTERNALERROR> Failed: Fixture "hana_system" called directly. Fixtures are not meant to be called directly,
INTERNALERROR> but are created automatically when test functions request them as parameters.
INTERNALERROR> See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
INTERNALERROR> https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
ERROR: InvocationError for command '/home/xarbulu/Workspace/sap_squad/PyHDB/.tox/py33/bin/py.test' (exited with code 3)
```

**Comment by arbulu89** [comment]
I have done more research on that, and with an older version of py.test works (tested with 3.3.2).

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
