### ISSUE TITLE
conn.close() raises exception

### ISSUE THREAD

**Issue by amarvin** [SAP/PyHDB#135]
Seems like conn.close() raises an exception that just says the connection is closed. Why is the exception raised, if closing the connection is the purpose of the function?

```python
>>> conn = pyhdb.connect(**credentials)
>>> conn.isconnected()
True
>>> conn.close()
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyhdb\connection.py", line 97, in __send_message_recv_reply
    raw_header = self._socket.recv(32)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyhdb\connection.py", line 168, in close
    reply = self.send_request(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyhdb\connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyhdb\connection.py", line 121, in __send_message_recv_reply
    raise OperationalError("Lost connection to HANA server (%r)" % error)
pyhdb.exceptions.OperationalError: Lost connection to HANA server (ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
