### ISSUE TITLE
LookupError: unknown encoding: cesu-8

### ISSUE THREAD

**Issue by DanieleMele** [SAP/PyHDB#149]
Trying to connect to SAP HANA give error: 
Traceback (most recent call last):
  File "C:\Users\u210990\IdeaProjects\wp3_daten_transfer\lesen_daten_hana.py", line 22, in <module>
    connection(host, port, user, pwd, sql)
  File "C:\Users\u210990\IdeaProjects\wp3_daten_transfer\lesen_daten_hana.py", line 16, in connection
    connection_parameter = pyhdb.connect(host=host_conn, port=port_conn, user=user_conn,
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\__init__.py", line 30, in connect
    conn.connect()
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\connection.py", line 141, in connect
    agreed_auth_part = self._auth_manager.perform_handshake()
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\auth.py", line 50, in perform_handshake
    response = self.connection.send_request(request)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\connection.py", line 83, in send_request
    payload = message.pack()  # obtain BytesIO instance
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\message.py", line 55, in pack
    self.build_payload(payload)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\message.py", line 45, in build_payload
    segment.pack(payload, commit=self.autocommit)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\segments.py", line 94, in pack
    self.build_payload(payload)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\segments.py", line 80, in build_payload
    part_payload = part.pack(remaining_size)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\parts.py", line 103, in pack
    arguments_count, payload = self.pack_data(remaining_size - self.header_size)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\parts.py", line 591, in pack_data
    payload = Fields.pack_data(fields)
  File "c:\devsbb\eaio\python3\lib\site-packages\pyhdb\protocol\parts.py", line 48, in pack_data
    field = field.encode('cesu-8')
LookupError: unknown encoding: cesu-8

I'm not sure if it is related to the python version 3.9?

**Comment by julymartiinez** [comment]
I'm also getting the same error. 
LookupError: unknown encoding: cesu-8

**Comment by skiastory** [comment]
Related with this issue, I opened the PR.
https://github.com/SAP/PyHDB/pull/150
Simple changing the encoding name 'cesu-8' to 'cesu8' might help you.

**Comment by yangjinglean** [comment]
I'm also getting the same error, Mac OS Mojave + Python 3.9.0
LookupError: unknown encoding: cesu-8

**Comment by ChethanChandra** [comment]
I'm also getting the same error, Mac OS Big Sur 11.2.3 + Python 3.9.0
LookupError: unknown encoding: cesu-8

I dont get where to simply change the encoding name from 'cesu-8' to 'cesu8'.
If its the DB server, my DBA will not budge.

**Comment by skiastory** [comment]
@ChethanChandra 
You can find what to be changed from this link:
https://github.com/SAP/PyHDB/pull/150/commits/507a105a574f3a205ebf7c2f0a734ffa8fa22431
Apply these changes onto your local repository. And then, install this modified package from your local repo.

**Comment by akdor1154** [comment]
workaround without patching:
```
import pyhdb.cesu8
import codecs
codecs.register(lambda s: (
	pyhdb.cesu8.CESU8_CODEC_INFO
	if s in {'cesu-8', 'cesu_8'}
	else None
))
```

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
