### ISSUE TITLE
ConfigParser.NoSectionError: No Section: 'formatters'

### ISSUE THREAD

**Issue by ricarda-schueler** [SAP/PyHDB#24]
I installed pyhdb via cloning the git and executing the setup.py.
While importing pyhdb the following error appears:

```
>>> import pyhdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyhdb-0.2.1-py2.7.egg/pyhdb/__init__.py", line 20, in <module>
    logging.config.fileConfig(os.path.join(this_dir, 'logging.conf'))
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters''
```
When starting the python console in the pyhdb directory and importing pyhdb there, there is no problem.

**Comment by ralhei** [comment]
Hi Ricarda,
      
      we fixed this problem just an hour ago, can you please update your
      local repo, then it should work. Sorry for the inconveniences,
      
      Ralph
      
      On 28.04.15 12:01, Ricarda Schueler wrote:
    
    
      I installed pyhdb via cloning the git and executing the
        setup.py.
        While importing pyhdb the following error appears:
      >>> import pyhdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyhdb-0.2.1-py2.7.egg/pyhdb/__init__.py", line 20, in <module>
    logging.config.fileConfig(os.path.join(this_dir, 'logging.conf'))
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters''

      When starting the python console in the pyhdb directory and
        importing pyhdb there, there is no problem.
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by ricarda-schueler** [comment]
Hi Ralph, 
Thanks for the quick response. Everything is working now.
