### ISSUE TITLE
No module named lib.tracing

### ISSUE THREAD

**Issue by jaheba** [SAP/PyHDB#25]
```
import pyhdb
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "pyhdb/__init__.py", line 23, in <module>
   from pyhdb.connection import Connection
 File "pyhdb/connection.py", line 22, in <module>
   from pyhdb.auth import AuthManager
 File "pyhdb/auth.py", line 24, in <module>
   from pyhdb.protocol.message import RequestMessage
 File "pyhdb/protocol/message.py", line 21, in <module>
   from pyhdb.lib.tracing import trace
ImportError: No module named lib.tracing
```

Seems that the `lib`-package is not included in the repository.

Commit: b50c790a2a772afa35695526ca8b42bf745224c3

**Comment by ralhei** [comment]
Sorry, seems to have been missed when pushing to github. The module is now available.
