### ISSUE TITLE
Support for Timestamp, Time and Date

### ISSUE THREAD

**Issue by mathebox** [SAP/PyHDB#30]
When trying to insert a datetime value with the following statement
```python
params = [0, datetime.datetime.now()]
cursor.executemany('INSERT INTO TEST_DATETIME VALUES (?, ?)', params)
connection.commit()
```
this error is thrown
```bash
Traceback (most recent call last):
  File "datetime-test.py", line 32, in <module>
    cursor.execute('INSERT INTO TEST_DATETIME VALUES (?, ?)', params)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/cursor.py", line 254, in execute
    self.executemany(statement, parameters=[parameters])
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/cursor.py", line 278, in executemany
    self.execute_prepared(prepared_statement, parameters)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/cursor.py", line 185, in execute_prepared
    response = self.connection.send_request(request)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/connection.py", line 83, in send_request
    payload = message.pack()  # obtain BytesIO instance
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/message.py", line 54, in pack
    self.build_payload(payload)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/message.py", line 44, in build_payload
    segment.pack(payload, commit=self.autocommit)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/segments.py", line 109, in pack
    self.build_payload(payload)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/segments.py", line 95, in build_payload
    part_payload = part.pack(remaining_size)
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/parts.py", line 100, in pack
    arguments_count, payload = self.pack_data()
  File "/Users/max/virtualenvs/hana_load/lib/python2.7/site-packages/pyhdb-0.2.3-py2.7.egg/pyhdb/protocol/parts.py", line 408, in pack_data
    pfield = _DataType.prepare(value)
AttributeError: type object 'Timestamp' has no attribute 'prepare'
```
The class method `prepare` is missing for the type object `Timestamp` to convert the value into binary format. The same applies for the type object `Time`.
The type object `Date` implements the `prepare` method. But the value is not properly stored in the database.

- - -

Create statement for the table `TEST_DATETIME`:
```sql
CREATE TABLE TEST_DATETIME (ID INTEGER, dt TIMESTAMP);
```

**Comment by ralhei** [comment]
In Pull request https://github.com/SAP/PyHDB/pull/28 at least the timestamp problem should be solved. Once this pull request is accepted you should be able to use it.

**Comment by bsrdjan** [comment]
@mathebox, the PR is merged, would you please check ?

**Comment by mathebox** [comment]
Yes, it's working. Thanks!
I've created a pull request #32 that fixes the insert of date and time values.
