### ISSUE TITLE
socket.error: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by lulucs** [SAP/PyHDB#58]
Hi All,
I tried to connect to my SAP HANA AWS,  host is my Public DNS, port 30015, user and password as ones I connect the server from eclipse,  but get following error:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Library/Python/2.7/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/Library/Python/2.7/site-packages/pyhdb/connection.py", line 137, in connect
    self._open_socket_and_init_protocoll()
  File "/Library/Python/2.7/site-packages/pyhdb/connection.py", line 66, in _open_socket_and_init_protocoll
    self._socket = socket.create_connection((self.host, self.port), self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 61] Connection refused
```

Any help is appreciated!

Thanks!

**Comment by ralhei** [comment]
Hi lulucs,
    this is probably not related to pyhdb but rather a basic
      connectivity problem with your HANA instance - it seems like it is
      not reachable from whereever you try it. 
    
    I have a trial HANA cloud platform (HPC) instance, and for being
      able to connect to it I have to use a proxy/tunnel tool (see
      https://tools.hana.ondemand.com), maybe your AWS installation
      requires something similar. But this is just a guess ...
    Ralph
    
    On 26.04.16 19:37, lulucs wrote:
    
    
      Hi All,
        I tried to connect to my SAP HANA AWS, host is my Public DNS,
        port 30015, user and password as ones I connect the server from
        eclipse, but get following error:
      Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Library/Python/2.7/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/Library/Python/2.7/site-packages/pyhdb/connection.py", line 137, in connect
    self._open_socket_and_init_protocoll()
  File "/Library/Python/2.7/site-packages/pyhdb/connection.py", line 66, in _open_socket_and_init_protocoll
    self._socket = socket.create_connection((self.host, self.port), self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 61] Connection refused

      Any help is appreciated!
      Thanks!
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view it on
          GitHub

**Comment by lulucs** [comment]
@ralhei Hi Ralph, thanks for the suggestion! I'll try this out and let you know how this goes.

**Comment by bsrdjan** [comment]
The guide might be helpful http://scn.sap.com/community/developer-center/hana/blog/2015/04/24/try-hanatrial-using-python-or-nodejs

**Comment by jarus** [comment]
Please reopen if the problem still exist and is related to PyHDB.
