### ISSUE TITLE
PyHDB doesn't work with Jython 2.7.0

### ISSUE THREAD

**Issue by fed239** [SAP/PyHDB#61]
Here is exception, which I get

```
>>> connection = pyhdb.connect(host="hana", port=30215, user="user", password="password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/connection.py", line 141, in connect
    agreed_auth_part = self._auth_manager.perform_handshake()
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/auth.py", line 50, in perform_handshake
    response = self.connection.send_request(request)
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/connection.py", line 98, in _Connection__send_message_recv_reply
    header = ReplyMessage.header_from_raw_header_data(raw_header)
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/connection.py", line 98, in _Connection__send_message_recv_reply
    header = ReplyMessage.header_from_raw_header_data(raw_header)
  File "/Users/fedor/jenv/Lib/site-packages/pyhdb/protocol/message.py", line 107, in header_from_raw_header_data
    raise Exception("Invalid message header received")
Exception: Invalid message header received
```

Same call works with normal Python

**Comment by jarus** [comment]
I'm sorry, I didn't test PyHDB with Jython. If you provide a pull request to fix this problem then I'm happy to review it.

Best regards
Christoph
