### ISSUE TITLE
Warnings are treated as errors

### ISSUE THREAD

**Issue by sergenovitski** [SAP/PyHDB#93]
I have a procedure in HANA that, when I run it in HANA Studio runs successfully but returns a warning:

_java.sql.SQLWarning: Not recommended feature: DDL statement is used in Dynamic SQL (current dynamic_sql_ddl_error_level = 1)_

Unfortunately I do need to use dynamic SQL in that case, so I was planning to ignore the warning.
However, when I try to run the same procedure using PyHDB, my script fails:

_$ python /opt/workflow/scripts/hana/call_procedure_env.py "flatten_sales_territories()" prod
Traceback (most recent call last):
  File "/opt/workflow/scripts/hana/call_procedure_env.py", line 26, in <module>
    cursor_h.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/cursor.py", line 258, in execute
    self._execute_direct(statement)
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/cursor.py", line 217, in _execute_direct
    reply = self.connection.send_request(request)
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/connection.py", line 124, in __send_message_recv_reply
    return ReplyMessage.unpack_reply(header, payload)
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/protocol/message.py", line 92, in unpack_reply
    segments=tuple(ReplySegment.unpack_from(payload, expected_segments=header.num_segments)),
  File "/usr/local/lib/python2.7/dist-packages/pyhdb/protocol/segments.py", line 150, in unpack_from
    raise Exception("Rows affected %s" % (error.parts[0].values,))
Exception: Rows affected (65934,)_

Is it possible to allow the library to ignore warnings?

**Comment by TwoLaid** [comment]
Have you tried wrapping the query execution in a `try`-`catch` block ? That should do the trick. 

Although, I do think that in the long run, pyHDB should support ignoring these warnings

**Comment by isansahoo123** [comment]
Having same issue. Getting below warning but my python program fails. I have try - Exception block is my code and when warning is encountered, it goes into the exception block and terminates the program. 
`java.sql.SQLWarning: Not recommended feature: DDL statement is used in Dynamic SQL (current dynamic_sql_ddl_error_level = 1)`

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
