### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made

### ISSUE THREAD

**Issue by dilshaat** [SAP/PyHDB#97]
I have access to a remote on premise SAP HANA DB server via VPN. VPN connection is done via NetExtender(DELL) and IP of HANA is a local one 192.168.3.50(e.g.). So, I can ping this IP address and I made a connection to this remote HANA server via SAP GUI as well. Here I am trying to connect with PyHDB:  

`import pyhdb
conn = pyhdb.connect(host="192.168.3.50", port=30015, user="db_user", password="pw")
cursor = conn.cursor()
cursor.execute("SELECT 'Hello Python World' FROM DUMMY")
cursor.fetchone()
cursor.close()`

I am getting this error:

`Traceback (most recent call last):
  File ".\test_hdb.py", line 3, in <module>
    conn = pyhdb.connect(host="192.168.3.50", port=30015, user="db_user", password="pw")
  File "C:\Users\dilsh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhdb\__init__.py", line 30, in connect
    conn.connect()
  File "C:\Users\dilsh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhdb\connection.py", line 137, in connect
    self._open_socket_and_init_protocoll()
  File "C:\Users\dilsh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhdb\connection.py", line 66, in _open_socket_and_init_protocoll
    self._socket = socket.create_connection((self.host, self.port), self._timeout)
  File "C:\Users\dilsh\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\dilsh\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it`

**Comment by MoonKang** [comment]
I am getting the same error

**Comment by jarus** [comment]
Could you maybe test connectivity with the hdbsql client provided from the SAP HANA Client Package. Based on the error message it looks like a problem while establishing the TCP connection: `No connection could be made because the target machine actively refused it`.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
